### ISSUE TITLE
several bugs i would like to report

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [tukasa0001/TownOfHost#722]
~~1. as arsonist when i douse everyone in oil i dont have a vent button :(~~
2. sometimes the arsonist douse cooldown doesn't trigger allowing multiple people to be doused at once
~~3. sometimes when the executioners target is ejected the game doesn't end~~
~~4. when the executioners target disconnects the executioner doesn't turn into jester~~
~~5. when the schrodinger cat is killed they die normally~~
~~6. the sniper is just very hit or miss 90% of the time the target doesn't die~~
all of these issues are on the latest version 2.0.3

**Comment by soukunsandesu** [comment]
We know 1, 2, 3 Issues.
1,3 Issues are fixed in develop version

**Comment by Kainqui** [comment]
> 4 issue fixed.

unfortunately, this issue is back as I got it today. Also, had a game where a Imp and a Jester were also lovers (a lover cannot have a neutral role). regardless, lovers were together at the final 3 and game did not end.

**Comment by soukunsandesu** [comment]
``5. when the schrodinger cat is killed they die normally``

If you hit it repeatedly, you will die.

**Comment by soukunsandesu** [comment]
``2. sometimes the arsonist douse cooldown doesn't trigger allowing multiple people to be doused at once``
Can't fix
